name: LinkButton
struct: Link
template: linkbutton_base.templ
variants:
  - name: Primary
    prefix: linkbtnprimary
    props:
      bgClass: bg-primary
  - name: Secondary
    prefix: linkbtnsecondary
    props:
      bgClass: bg-secondary
  - name: Tertiary
    prefix: linkbtntertiary
    props:
      bgClass: bg-tertiary
  - name: Quaternary
    prefix: linkbtnquaternary
    props:
      bgClass: bg-quaternary
  - name: Accent
    prefix: linkbtnaccent
    props:
      bgClass: bg-accent
  - name: Unique
    prefix: linkbtnunique
    props:
      bgClass: bg-unique
  - name: Attention
    prefix: linkbtnattention
    props:
      bgClass: bg-attention
  - name: Transparent
    prefix: linkbtntransparent
    props:
      bgClass: bg-transparent
