name: Radio
struct: Radio
template: radio_base.templ

variants:
  - name: Primary
    prefix: radioprimary
    props:
      bgClass: bg-primary

  - name: Secondary
    prefix: radiosecondary
    props:
      bgClass: bg-secondary

  - name: Tertiary
    prefix: radiotertiary
    props:
      bgClass: bg-tertiary

  - name: Accent
    prefix: radioaccent
    props:
      bgClass: bg-accent

  - name: Unique
    prefix: radiounique
    props:
      bgClass: bg-unique

  - name: Attention
    prefix: radioattention
    props:
      bgClass: bg-attention
